"""empty message

Revision ID: 410490d7dc5b
Revises: c586e85915b2
Create Date: 2022-08-06 14:06:24.075547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '410490d7dc5b'
down_revision = 'c586e85915b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_poke',
    sa.Column('pokemon_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pokemon_id'], ['pokemon.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_poke')
    # ### end Alembic commands ###
