"""empty message

Revision ID: a1494d9cc047
Revises: ed89b4b2bf3c
Create Date: 2022-08-06 12:34:22.898150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1494d9cc047'
down_revision = 'ed89b4b2bf3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pokemon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('ability', sa.String(), nullable=True),
    sa.Column('base_experience', sa.String(), nullable=True),
    sa.Column('attack_base_stat', sa.String(), nullable=True),
    sa.Column('hp_base_stat', sa.String(), nullable=True),
    sa.Column('defense_stat', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pokemon')
    # ### end Alembic commands ###
