"""empty message

Revision ID: c586e85915b2
Revises: a1494d9cc047
Create Date: 2022-08-06 12:35:10.668120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c586e85915b2'
down_revision = 'a1494d9cc047'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('pokemon', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'pokemon', ['pokemon'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'pokemon')
    # ### end Alembic commands ###
